#ifndef _USER_TERM_H_
#define _USER_TERM_H_

//#include "ftms_cpu.h"

#define _POLLING_DATA_RDY_		0x30
#define _POLLING_DATA_EMPTY_		0x31

#define EXIT_CHAR			0x1b
#define NUL        			0x00 

/*
#define MAIN_MENU_STAT			0	
#define MAIN_CONFIG_MENU		1	
#define REALTIME_MONITOR_MODE		2	
#define	POLLING_MONITOR_MODE		3
#define	DATA_SAVE_MENU			4
*/

typedef enum {
	MAIN_MENU_STAT = 0,
	MAIN_CONFIG_MENU, 
	REALTIME_MONITOR_MODE,
	POLLING_MONITOR_MODE,
	DATA_SAVE_MENU,
	TEST_SYSTEM_MENU,
	RESET_SYSTEM,
	HIDDEN_MANAGE_MENU,
	BOARD_TEST_MENU,
	// config main controller
	INPUT_TIME_STAT,
	INPUT_ADDR_STAT,
	CONFIG_IP_ADDR,
	CONFIG_SUBNET_MSK,
	CONFIG_GATEWAY_IP,
	CONFIG_SERVER_IP,
	CONFIG_SERVER_PORT,
	CONFIG_TUNNEL_ID,
	CONFIG_CONTROLLER_ID,
	CONFIG_SYNC,
	CONFIG_MAX_LOOP,
	CONFIG_GAP_LOOP,
	// CONFIG_DIR_STAT,
	INIT_VOL_STAT,
	SET_NUM_SUB_CON,
	RESET_MAIN_CON,
	
	PRINT_RT_BY_INDEX,
	PRINT_PL_BY_INDEX,
	PRINT_LASTEST_RT,
	PRINT_LASTEST_PL,
	SEND_RT_SAVE_MODE,
	SEND_PL_SAVE_MODE,
	// debug mode
	DEBUG_MONITOR_MODE,
	// Hidden Manage Menu
	DEFAULT_PARAM,
} USER_TERM_STAT;


//USER_TERM_STAT term_stat = MAIN_MENU_STAT;

uint8 polling_disp_flg;
uint8 term_stat;

#endif /* _USER_TERM_H_ */

